//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicrosLabel.Domain.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MicrosLabel.Domain.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sql consult must contains where with sku and clientcode..
        /// </summary>
        internal static string InvalidSqlConsult {
            get {
                return ResourceManager.GetString("InvalidSqlConsult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sql must return all Zpl parameters..
        /// </summary>
        internal static string InvalidSqlParameters {
            get {
                return ResourceManager.GetString("InvalidSqlParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los valores no pueden ir vacíos o en Null..
        /// </summary>
        internal static string Null {
            get {
                return ResourceManager.GetString("Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Template, Zpl and Sql can&apos;t have empty or null values..
        /// </summary>
        internal static string NullT_Z_S {
            get {
                return ResourceManager.GetString("NullT-Z-S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dpi must be between 1 y 3000..
        /// </summary>
        internal static string OutOfRangeDpi {
            get {
                return ResourceManager.GetString("OutOfRangeDpi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LabelType must be 0 , 1, 2, 3 or 4..
        /// </summary>
        internal static string OutOfRangeLabelType {
            get {
                return ResourceManager.GetString("OutOfRangeLabelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sql Inyection..
        /// </summary>
        internal static string SqlInyection {
            get {
                return ResourceManager.GetString("SqlInyection", resourceCulture);
            }
        }
    }
}
