//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicrosLabel.Application.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MicrosLabel.Application.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This label already exist and cnnot be added..
        /// </summary>
        internal static string AlExistLabel {
            get {
                return ResourceManager.GetString("AlExistLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This client don&apos;t exist and cannot be created...
        /// </summary>
        internal static string ExistClient {
            get {
                return ResourceManager.GetString("ExistClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This client code already exist and client cannot be created..
        /// </summary>
        internal static string ExistClientCode {
            get {
                return ResourceManager.GetString("ExistClientCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This configuration&apos;s client don&apos;t exist and  cannot be created..
        /// </summary>
        internal static string ExistClientConfAdd {
            get {
                return ResourceManager.GetString("ExistClientConfAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This configuration&apos;s client don&apos;t exist and cannot be updated..
        /// </summary>
        internal static string ExistClientConfPut {
            get {
                return ResourceManager.GetString("ExistClientConfPut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This client name already exist and client cannot be created..
        /// </summary>
        internal static string ExistClientName {
            get {
                return ResourceManager.GetString("ExistClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This configuration already exist and cannot be created..
        /// </summary>
        internal static string ExistConfigurationAdd {
            get {
                return ResourceManager.GetString("ExistConfigurationAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This configuration don&apos;t exist and cannot be deleted..
        /// </summary>
        internal static string ExistConfigurationDel {
            get {
                return ResourceManager.GetString("ExistConfigurationDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This configuration don&apos;t exist and cannot be updated..
        /// </summary>
        internal static string ExistConfigurationPut {
            get {
                return ResourceManager.GetString("ExistConfigurationPut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This label not exist and cannot be form..
        /// </summary>
        internal static string ExistLabel {
            get {
                return ResourceManager.GetString("ExistLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This configuration&apos;s label don&apos;t exist and  cannot be created..
        /// </summary>
        internal static string ExistLabelConfAdd {
            get {
                return ResourceManager.GetString("ExistLabelConfAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This configuration&apos;s label don&apos;t exist and cannot be updated..
        /// </summary>
        internal static string ExistLabelConfPut {
            get {
                return ResourceManager.GetString("ExistLabelConfPut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This label don&apos;t exist and cannot be deleted..
        /// </summary>
        internal static string ExistLabelDel {
            get {
                return ResourceManager.GetString("ExistLabelDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This label don&apos;t exist and cannot be updated..
        /// </summary>
        internal static string ExistLabelPut {
            get {
                return ResourceManager.GetString("ExistLabelPut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This label hasn&apos;t configurations and cannot be form..
        /// </summary>
        internal static string NotRelaction {
            get {
                return ResourceManager.GetString("NotRelaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This client has labels configurations and cannot be deleted..
        /// </summary>
        internal static string RelactionClient {
            get {
                return ResourceManager.GetString("RelactionClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This label has configurations and cannot be deleted..
        /// </summary>
        internal static string RelactionLabel {
            get {
                return ResourceManager.GetString("RelactionLabel", resourceCulture);
            }
        }
    }
}
